services:
  server:
    image: go-fast-cdn
    build: .
    ports:
      - "8070:8080"
    volumes:
      - /home/go-fast-cdn/uploads:/app/uploads
      - /home/go-fast-cdn/db_data:/app/db_data
    container_name: go-fast-cdn
    networks: 
      - casa
networks:
  casa:
    external: true
